version: "3"

services:
  pterodactyl-panel:
    build: 
      context: panel
      dockerfile: Dockerfile
    restart: "no"
    env_file:
      - .env
    ports:
      - "80:80"
    links: 
      - redis
      - mysql
    # expose:
      # Opens port 3306 on the container
      # - '80'
      # Where our data will be persisted
    volumes:
      - ./log:/var/log/nginx/
  redis:
    image: redis:alpine
    restart: "no"
    command: redis-server --requirepass redispw
    env_file:
      - .env
    environment:
     - REDIS_REPLICATION_MODE=master
  mysql:
    image: mysql:5.7
    restart: "no"
    env_file:
      - .env
